truncate table SYSTEM_PARAMETER;
insert into SYSTEM_PARAMETER(PARAMETER_ID,CREATED_BY,DATE_CREATED,NAME,VALUE,PARAMETER_TYPE)
values(1,"SYSTEM",now(),"0-2","0-2 Years","EXPERIENCE");
insert into SYSTEM_PARAMETER(PARAMETER_ID,CREATED_BY,DATE_CREATED,NAME,VALUE,PARAMETER_TYPE)
values(2,"SYSTEM",now(),"2-4","2-4 Years","EXPERIENCE");
insert into SYSTEM_PARAMETER(PARAMETER_ID,CREATED_BY,DATE_CREATED,NAME,VALUE,PARAMETER_TYPE)
values(3,"SYSTEM",now(),"4-6","4-6 Years","EXPERIENCE");
insert into SYSTEM_PARAMETER(PARAMETER_ID,CREATED_BY,DATE_CREATED,NAME,VALUE,PARAMETER_TYPE)
values(4,"SYSTEM",now(),"6-8","6-8 Years","EXPERIENCE");
insert into SYSTEM_PARAMETER(PARAMETER_ID,CREATED_BY,DATE_CREATED,NAME,VALUE,PARAMETER_TYPE)
values(5,"SYSTEM",now(),"8-10","8-10 Years","EXPERIENCE");
insert into SYSTEM_PARAMETER(PARAMETER_ID,CREATED_BY,DATE_CREATED,NAME,VALUE,PARAMETER_TYPE)
values(6,"SYSTEM",now(),"10-50","more than 10 Years","EXPERIENCE");

insert into SYSTEM_PARAMETER(PARAMETER_ID,CREATED_BY,DATE_CREATED,NAME,VALUE,PARAMETER_TYPE)
values(7,"SYSTEM",now(),"Expert","Expert","COMPETENCY-RATING");
insert into SYSTEM_PARAMETER(PARAMETER_ID,CREATED_BY,DATE_CREATED,NAME,VALUE,PARAMETER_TYPE)
values(8,"SYSTEM",now(),"Intermediate","Intermediate","COMPETENCY-RATING");
insert into SYSTEM_PARAMETER(PARAMETER_ID,CREATED_BY,DATE_CREATED,NAME,VALUE,PARAMETER_TYPE)
values(9,"SYSTEM",now(),"Beginner","Beginner","COMPETENCY-RATING");

insert into SYSTEM_PARAMETER(PARAMETER_ID,CREATED_BY,DATE_CREATED,NAME,VALUE,PARAMETER_TYPE)
values(10,"SYSTEM",now(),"","7","DEALLOCATION_INTIMATION_DAYS");

commit;